package com.webservice.cxf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-03-15T00:33:22.354+08:00
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "MyServiceImplService", 
                  wsdlLocation = "http://localhost:8080/webservice_cxf/webservice/service?wsdl",
                  targetNamespace = "http://cxf.webservice.com/") 
public class MyServiceImplService extends javax.xml.ws.Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://cxf.webservice.com/", "MyServiceImplService");
    public final static QName ServicePort = new QName("http://cxf.webservice.com/", "servicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/webservice_cxf/webservice/service?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MyServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/webservice_cxf/webservice/service?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MyServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MyServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public MyServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MyServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MyServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns Service
     */
    @WebEndpoint(name = "servicePort")
    public Service getServicePort() {
        return super.getPort(ServicePort, Service.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Service
     */
    @WebEndpoint(name = "servicePort")
    public Service getServicePort(WebServiceFeature... features) {
        return super.getPort(ServicePort, Service.class, features);
    }

}
