package com.webservice.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-03-15T00:33:22.301+08:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://cxf.webservice.com/", name = "service")
@XmlSeeAlso({ObjectFactory.class})
public interface Service {

    @WebMethod
    @RequestWrapper(localName = "getRoles", targetNamespace = "http://cxf.webservice.com/", className = "com.webservice.cxf.GetRoles")
    @ResponseWrapper(localName = "getRolesResponse", targetNamespace = "http://cxf.webservice.com/", className = "com.webservice.cxf.GetRolesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.webservice.cxf.MyRoleArray getRoles();

    @WebMethod
    @RequestWrapper(localName = "getRolesByUser", targetNamespace = "http://cxf.webservice.com/", className = "com.webservice.cxf.GetRolesByUser")
    @ResponseWrapper(localName = "getRolesByUserResponse", targetNamespace = "http://cxf.webservice.com/", className = "com.webservice.cxf.GetRolesByUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.webservice.cxf.Role> getRolesByUser(
        @WebParam(name = "arg0", targetNamespace = "")
        com.webservice.cxf.User arg0
    );

    @WebMethod
    @RequestWrapper(localName = "add", targetNamespace = "http://cxf.webservice.com/", className = "com.webservice.cxf.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://cxf.webservice.com/", className = "com.webservice.cxf.AddResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );
}
